name: build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: build_svc
      run: go build -ldflags "-s -w" -o build/mainflux-license-svc cmd/service/main.go
    - name: build_agent
      run: go build -ldflags "-s -w" -o build/mainflux-license-agent cmd/agent/main.go
